app/quotations/__init__.py
from flask import Blueprint

quotations = Blueprint('quotations', __name__)

from . import views

app/quotations/views.py
from flask import render_template, redirect, url_for, request, flash, abort, jsonify
from flask_login import login_required, current_user
from . import quotations
from ..models import Cliente, Cotizacion, Producto
from .. import db
import json
from ..utils import cantidad_letra_from_float

@quotations.route('/elegir-cliente', methods=['GET', 'POST'])
@login_required
def elegir_cliente():
    """
    Este recurso sirve de prompt para especificar el cliente para el que se genera 
    una nueva cotización. La elección se hace por nombre corto de cada cliente. Se
    redirecciona al recurso categorias indicando en la URL el nombre corto 
    del cliente.
    """
    if request.method == 'POST':
        cliente_nombre_corto = request.form['cliente']
        return redirect(url_for('quotations.categorias', cliente=cliente_nombre_corto))
    else:
        clientes = [cliente.nombre_corto for cliente in current_user.clientes]
        print(clientes)
        return render_template('quotations/elegir_cliente.html', clientes=clientes)

@quotations.route('/categorias/<string:cliente>', methods=['GET', 'POST'])
@login_required
def categorias(cliente):
    """
    Este recurso sirve de prompt para solicitar el número de categorias [distintas]
    de productos por cliente que van a cotizarse. Se redirecciona al recurso nueva_cotizacion
    exportando el número de categorias.
    """
    current_cliente = Cliente.query.filter_by(nombre_corto=cliente).first()
    total_categorias_productos = len([producto for producto in current_cliente.productos])
    if request.method == 'POST':
        categorias_a_cotizar = int(request.form['categorias'])
        return redirect(url_for('quotations.nueva_cotizacion', cliente=cliente, categorias_a_cotizar=categorias_a_cotizar))
    else:
        return render_template('quotations/categorias.html', cliente=cliente, total_categorias_productos=total_categorias_productos)

@quotations.route('/nueva-cotizacion/<string:cliente>/<int:categorias_a_cotizar>', methods=['GET', 'POST'])
@login_required
def nueva_cotizacion(cliente, categorias_a_cotizar):
    """
    Recurso que importa la información de los productos y número de categorías a cotizar.
    """
    current_cliente = Cliente.query.filter_by(nombre_corto=cliente).first()
    total_categorias_productos = len([producto for producto in current_cliente.productos])
    if request.method == 'POST':
        dict_info_cotizacion = request.form.to_dict()
        pedido = {'productos': {}}
        for categoria in range(categorias_a_cotizar):
            pedido['productos'][categoria] = dict([
                ('objProducto', Producto.query.filter_by(sku=dict_info_cotizacion[f'producto{categoria}']).first()),
                ('cantidad', dict_info_cotizacion[f'cantidad-producto{categoria}']),
                ('descripcion_adicional', dict_info_cotizacion[f'descripcion-adicional-producto{categoria}']),
                ('notas', dict_info_cotizacion[f'notas-producto{categoria}']),
                ('importe', 0)
            ])
        pedido['tiempo_entrega_dias'] = dict_info_cotizacion['tiempo-entrega-dias']
        pedido['pago_anticipado'] = dict_info_cotizacion['pago-anticipado']
        # print(json.dumps(pedido, indent=4))
        # Cálculo de importe por producto: precio_unitario*cantidad
        # Cálculo de subtotal: suma_i(importe_i)
        subtotal = 0
        for item in pedido['productos'].keys():
            importe = 0
            importe += float(pedido['productos'][item]['objProducto'].precio_unitario)*int(pedido['productos'][item]['cantidad'])
            pedido['productos'][item]['importe'] = importe
            subtotal += importe
            
        pedido['subtotal'] = subtotal
        # Cálculo del IVA
        iva = 0.16*subtotal
        total = subtotal + iva
        parte_entera, centavos = cantidad_letra_from_float(total)
        pedido['iva'] = iva
        pedido['total'] = total
        pedido['cantidad_letra'] = ' '.join([parte_entera, 'pesos', centavos + '/100', 'm.n.']).upper()
        print(pedido)
        return render_template('quotations/template_cotizacion.html', cliente=current_cliente, pedido=pedido)
    else:
        if not categorias_a_cotizar > total_categorias_productos:
            return render_template('quotations/nueva_cotizacion.html', cliente=current_cliente, categorias_a_cotizar=categorias_a_cotizar)
        else:
            abort(404)

@quotations.app_template_filter()
def number_format(cantidad):
    """
    Se da formato de moneda a una cantidad dada como string o como float.
    Ejemplo: '18100' --> '$ 18,100.00'
    """
    return '$ {:,.2f}'.format(float(cantidad)) if type(cantidad) is str else '$ {:,.2f}'.format(cantidad)

app/templates/quotations/categorias.html
{% extends "base.html" %}

{% block title %}Cotizaciones | Quoter{% endblock title %}

{% block page_content %}

<form action="{{ url_for('quotations.categorias', cliente=cliente) }}" method="POST">
    <p>
        <h2>¿Cuántas categorías de productos vas a cotizar?</h2>
    </p>
    <input type="number" name="categorias" value=0 min=0 max={{ total_categorias_productos }}>
    <p>
        <input type="submit" value="Siguiente" class="btn-submit">
    </p>
</form>

{% endblock page_content %}

app/templates/quotations/elegir_cliente.html
{% extends "base.html" %}

{% block title %}Cotizaciones | Quoter{% endblock title %}

{% block page_content %}

<header>
    <h1>¿Para qué cliente es la cotización?</h1>
</header>

<form action="{{ url_for('quotations.elegir_cliente') }}" method="POST">
    <select name="cliente">
        {% for cliente in clientes %}
        <option value="{{ cliente }}">{{ cliente }}</option>
        {% endfor %}
    </select>
    <p>
        <input type="submit" value="Siguiente" class="btn-submit">
    </p>
</form>

{% endblock page_content %}

app/templates/quotations/nueva_cotizacion.html
{% extends "base.html" %}

{% block title %}Nueva cotización | Quoter{% endblock title %}

{% block page_content %}

<header>
    <h1>Selecciona los productos a cotizar</h1>
</header>

<section>
    <div class="datos-cotizacion">
        <form action="{{ url_for('quotations.nueva_cotizacion', cliente=cliente.nombre_corto, categorias_a_cotizar=categorias_a_cotizar) }}" method="POST">
            {% for p in range(categorias_a_cotizar) %}
            <div>
                <label for="product-option">Producto:</label>
                <select name="producto{{ p }}" id="product-option">
                    {% for producto in cliente.productos %}
                    <option value="{{ producto.sku }}">{{ producto.descripcion }}</option>
                    {% endfor %}
                </select>
                <label for="cantidad">Cantidad:</label>
                <input type="number" name="cantidad-producto{{ p }}" id="cantidad" value=1 min=1 max=100><br>
                <br><label for="add-description">Descripción adicional:</label><br>
                <!-- <input type="text" size="50" name="descripcion-adicional-producto{#{ p }#}" id="add-description"><br> -->
                <textarea name="descripcion-adicional-producto{{ p }}" id="add-description" cols="30" rows="5"></textarea><br>
                <br><label for="notas">Notas:</label><br>
                <textarea name="notas-producto{{ p }}" id="notas" cols="30" rows="5"></textarea>
            </div><br><br>
            {% endfor %}
            <p>
                <h2>Detalles de la cotización</h2>
            </p>
            <label for="tiempo">Tiempo de entrega en días:</label><br>
            <input type="number" name="tiempo-entrega-dias" id="tiempo" value=1 min=1><br>
            <br><label for="pago-anticipado">Pago anticipado del</label><br>
            <input type="number" name="pago-anticipado" id="pago-anticipado" value=50 min=0 max=100>%
            <p>
                <br><center>
                    <input type="submit" value="Generar Cotización" class="btn-submit">
                </center>
            </p>
        </form>
    </div>
</section>

{% endblock page_content %}

app/templates/quotations/template_cotizacion.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cotización</title>
</head>

<body>
    <header>
        <h1>SEAL Suministros Industriales</h1>
    </header>

    <section>
        Cotización para: {{ cliente.razon_social }}
        Folio:
        <table>
            <thead>
                <tr>
                    <td>Cantidad</td>
                    <td>Unidad</td>
                    <td>Descripción</td>
                    <td>Precio Unitario</td>
                    <td>Importe</td>
                </tr>
            </thead>
            <tbody>
                {% for producto in pedido['productos'].keys() %}
                <tr>
                    <td>{{ pedido['productos'][producto]['cantidad'] }}</td>
                    <td>{{ pedido['productos'][producto]['objProducto'].medicion }}</td>
                    {% if not (pedido['productos'][producto]['descripcion_adicional'] or pedido['productos'][producto]['notas']) %}
                    <td>{{ pedido['productos'][producto]['objProducto'].descripcion }}</td>
                    {% elif (pedido['productos'][producto]['descripcion_adicional'] and not pedido['productos'][producto]['notas']) %}
                    <td>{{ pedido['productos'][producto]['objProducto'].descripcion }}<br>
                        {{ pedido['productos'][producto]['descripcion_adicional'] }}<br>
                    {% else %}
                    <td>{{ pedido['productos'][producto]['objProducto'].descripcion }}<br>
                        {{ pedido['productos'][producto]['descripcion_adicional'] }}<br>
                        {{ pedido['productos'][producto]['notas'] }}</td>
                    {% endif %}

                    <td>{{ pedido['productos'][producto]['objProducto'].precio_unitario | number_format }}</td>
                    <td>{{ pedido['productos'][producto]['importe'] | number_format }}</td>
                </tr>
                {% endfor %}
                <tr>
                    <td>Subtotal:</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>{{ pedido['subtotal'] | number_format }}</td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>IVA 16%</td>
                    <td>{{ pedido['iva'] | number_format }}</td>
                </tr>
                <tr>
                    <td>Total con letra:</td>
                    <td></td>
                    <td></td>
                    <td>Total:</td>
                    <td>{{ pedido['total'] | number_format }}</td>
                </tr>
            </tbody>
        </table>
        <p>
            ( {{ pedido['cantidad_letra'] }} )
        </p>
        <p>
            Tiempo de entrega: {{ pedido['tiempo_entrega_dias'] }} DÍAS
        </p>
        <p>
            Condiciones de pago: {{ pedido['pago_anticipado'] }}% ANTICIPO
        </p>
    </section>

</body>

</html>