app/products/__init__.py
from flask import Blueprint

products = Blueprint('products', __name__)

from . import views

app/products/views.py
from flask import render_template, redirect, request, flash, url_for
from flask_login import login_required, current_user
from . import products
from ..models import Cliente, Producto
from .. import db


@products.route('/<string:cliente>')
@login_required
def listado_productos(cliente):
    current_cliente = Cliente.query.filter_by(nombre_corto=cliente).first()
    return render_template('products/listado_productos.html', cliente=current_cliente)

# @products.route('/agregar-producto')
# Recurso para agregar un producto seleccionando el cliente al vuelo

@products.route('/agregar-producto/<string:cliente>', methods=['GET', 'POST'])
@login_required
def agregar_producto(cliente):
    """
    El único filtro por ahora de esta función es verificar en base de datos si ya existe el sku
    del producto a agregar.
    """
    current_cliente = Cliente.query.filter_by(nombre_corto=cliente).first()
    if request.method == 'POST':
        if Producto.query.filter_by(sku=request.form['sku']).first():
            flash('SKU previamente registrado')
            return redirect(request.url)
        else:
            nuevo_producto = Producto(cliente=current_cliente, sku=request.form['sku'], medicion=request.form['medicion'], descripcion=request.form['descripcion'], precio_unitario=request.form['precio_unitario'])
            db.session.add(nuevo_producto)
            db.session.commit()
            flash('Producto agregado satisfactoriamente')
            return redirect(url_for('products.listado_productos', cliente=current_cliente.nombre_corto))
    return render_template('products/agregar_producto.html', cliente=current_cliente)

@products.route('/editar-producto/<string:sku>', methods=['GET', 'POST'])
@login_required
def editar_producto(sku):
    """
    Función para modificar los datos de un producto. La recolección de los datos a modificar son buscados
    en base de datos usando el sku del producto. 
    """
    producto_a_editar = Producto.query.filter_by(sku=sku).first()
    current_cliente = Cliente.query.filter_by(id=producto_a_editar.cliente_id).first()
    if request.method == 'POST':
        for campo in request.form.keys():
            if len(request.form[campo]) > 0:
                setattr(producto_a_editar, campo, request.form[campo])
        db.session.add(producto_a_editar)
        db.session.commit()
        flash('Se han guardado los cambios')
        return redirect(url_for('products.listado_productos', cliente=current_cliente.nombre_corto))
    return render_template('products/editar_producto.html', producto=producto_a_editar, cliente=current_cliente)

app/templates/products/agregar_producto.html
{% extends "base.html" %}

{% block title %}Agregar producto | Quoter{% endblock title %}

{% block page_content %}

<section>
    <div>
        <form action="{{ url_for('products.agregar_producto', cliente=cliente.nombre_corto) }}" method="POST">
            <div>
                <input type="text" name="sku" id="sku" placeholder="SKU" required>
            </div>
            <div>
                <input type="text" name="medicion" id="medicion" placeholder="Unidad de Medida" required>
            </div>
            <div>
                <input type="text" name="descripcion" id="descripcion" placeholder="Descripción" required>
            </div>
            <div>
                <input type="text" name="precio_unitario" placeholder="Precio Unitario">
            </div>
            <div>
                <input type="submit" value="Agregar Producto">
            </div>
        </form>
    </div>
</section>

{% endblock page_content %}

app/templates/products/editar_producto.html
{% extends "base.html" %}

{% block title %}Editar producto | Quoter{% endblock title %}

{% block page_content %}

<section>
    <div>
        <form action="{{ url_for('products.editar_producto', sku=producto.sku) }}" method="POST">
            <div>
                <input type="text" name="sku" id="sku" value="{{ producto.sku }}" placeholder="SKU" required>
            </div>
            <div>
                <input type="text" name="medicion" id="medicion" value="{{ producto.medicion }}" placeholder="Unidad de Medida" required>
            </div>
            <div>
                <input type="text" name="descripcion" id="descripcion" value="{{ producto.descripcion }}" placeholder="Descripción" required>
            </div>
            <div>
                <input type="text" name="precio_unitario" value="{{ producto.precio_unitario }}" placeholder="Precio Unitario">
            </div>
            <div>
                <input type="submit" value="Guardar cambios"><a href="{{ url_for('products.listado_productos', cliente=cliente.nombre_corto) }}">Cancelar</a>
            </div>
        </form>
    </div>
</section>

{% endblock page_content %}

app/templates/products/listado_productos.html
{% extends "base.html" %}

{% block title %}Productos | Quoter{% endblock title %}

{% block page_content %}

<header>
    <h1>Listado de productos por cliente</h1>
</header>

<section>
    <div>
        <div>
            <p>
                <h2>{{ cliente.razon_social }}</h2>
            </p>
        </div>
        <table>
            <thead>
                <tr>
                    <td>SKU</td>
                    <td>Descripción</td>
                    <td>Precio Unitario</td>
                    <td>Modificar</td>
                </tr>
            </thead>
            <tbody>
                {% for producto in cliente.productos.all() %}
                <tr>
                    <td>{{ producto.sku }}</td>
                    <td>{{ producto.descripcion }}</td>
                    <td>{{ producto.precio_unitario }}</td>
                    <td>
                        <a href="{{ url_for('products.editar_producto', sku=producto.sku) }}">Ir</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>

<section>
    <div>
        <p>
            <a href="{{ url_for('products.agregar_producto', cliente=cliente.nombre_corto) }}">Agregar producto</a>
        </p>
    </div>
</section>

{% endblock page_content %}