app/clients/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, SubmitField
from wtforms.validators import DataRequired
from flask_login import current_user
from ..models import Cliente

class SelectClientForm(FlaskForm):
    # clients = [client.nombre_corto for client in Cliente.query.filter_by(usuario=current_user).all()]
    selected_client = SelectField('Selecciona un cliente', choices=['C++', 'Java'])
    submit = SubmitField('Enviar')

app/clients/__init__.py
from flask import Blueprint

clients = Blueprint('clients', __name__)

from . import views

app/clients/views.py
from flask import render_template, redirect, url_for, flash, request
from flask_login import login_required, current_user
from . import clients
from ..models import Cliente, Cotizacion
from .. import db

@clients.route('/', methods=['GET', 'POST'])
@login_required
def listado_clientes():
    clientes = Cliente.query.filter_by(usuario=current_user).all()
    return render_template('clients/listado_clientes.html', clientes=clientes)

@clients.route('/<string:cliente>')
@login_required
def historial(cliente):
    cliente_actual = Cliente.query.filter_by(nombre_corto=cliente).first()
    cotizaciones = Cotizacion.query.filter_by(cliente=cliente_actual).all()
    return render_template('clients/historial_cotizaciones.html', cliente=cliente_actual, cotizaciones=cotizaciones)

@clients.route('/agregar-cliente', methods=['GET', 'POST'])
@login_required
def agregar_cliente():
    if request.method == 'POST':
        print(request.form)
        nuevo_cliente = Cliente(usuario=current_user, razon_social=request.form['razon_social'], rfc=request.form['rfc'], nombre_corto=request.form['nombre_corto'], telefono=request.form['telefono'], calle_numero=request.form['calle_numero'], colonia=request.form['colonia'], municipio=request.form['municipio'], estado=request.form['estado'], cp=request.form['cp'])
        print(nuevo_cliente)
        db.session.add(nuevo_cliente)
        db.session.commit()
        flash('El cliente ha sido agregado satisfactoriamente')
        return redirect(url_for('clients.listado_clientes'))
    return render_template('clients/agregar_cliente.html')

@clients.route('/editar-cliente/<string:cliente>', methods=['GET', 'POST'])
@login_required
def editar_cliente(cliente):
    """
    Esta función NO compara los datos almacenados del cliente a modificar con los
    que se reciben en request.form. Se reescriben los campos en el registro correspondiente
    del cliente solamente si el dato modificado no es un string de longitud 0. 
    """
    cliente_a_editar = Cliente.query.filter_by(nombre_corto=cliente).first()
    if request.method == 'POST':
        for dato in request.form.keys():
            if len(request.form[dato]) > 0:
                setattr(cliente_a_editar, dato, request.form[dato])
        db.session.add(cliente_a_editar)
        db.session.commit()
        flash('Se han guardado los cambios')
        return redirect(url_for('clients.listado_clientes'))
    return render_template('clients/editar_cliente.html', cliente=cliente_a_editar)

# @clients.route('/', methods=['GET', 'POST'])
# @login_required
# def seleccionar_cliente():
#     clientes = [cliente.razon_social for cliente in Cliente.query.filter_by(usuario=current_user).all()]
#     if request.method == 'POST':
#         selected_client = Cliente.query.filter_by(razon_social=request.form['cliente']).first()
#         print(request.form['cliente'])
#         return redirect('/clientes/{}'.format(selected_client.nombre_corto))
#     return render_template('clients/seleccionar_cliente.html', clientes=clientes)

app/templates/clients/agregar_cliente.html
{% extends "base.html" %}

{% block title %}Agregar cliente | Quoter{% endblock title %}

{% block page_content %}

<section>
    <div>
        <form action="{{ url_for('clients.agregar_cliente') }}" method="POST">
            <div>
                <input type="text" name="razon_social" id="razon_social" placeholder="Razón Social" required>
            </div>
            <div>
                <input type="text" name="rfc" id="rfc" placeholder="RFC" required>
            </div>
            <div>
                <input type="text" name="nombre_corto" id="nombre_corto" placeholder="Nombre corto" required>
            </div>
            <div>
                <input type="text" name="telefono" placeholder="Teléfono de contacto">
            </div>
            <div>
                <input type="text" name="calle_numero" placeholder="Calle y número">
            </div>
            <div>
                <input type="text" name="colonia" placeholder="Colonia">
            </div>
            <div>
                <input type="text" name="municipio" placeholder="Municipio">
            </div>
            <div>
                <input type="text" name="estado" placeholder="Estado">
            </div>
            <div>
                <input type="text" name="cp" id="cp" placeholder="Código Postal">
            </div>
            <div>
                <input type="submit" value="Agregar Cliente">
            </div>
        </form>
    </div>
</section>

{% endblock page_content %}

{% block scripts %}
<script src="{{ url_for('static', filename='js/agregar_cliente.js') }}">
</script>
{% endblock scripts %}

app/templates/clients/cotizacion_seleccionar_cliente.html
{% extends "base.html" %}

{% block title %}Ver clientes | Quoter{% endblock %}

{% block page_content %}
<header>
    <h1>Seleccionar cliente</h1>
</header>
<form action="{{ url_for('clients.seleccionar_cliente') }}" method="POST">
    <div class="form-group">
        <select name="cliente">
            {% for cliente in clientes %}
            <option value="{{ cliente }}">{{ cliente }}</option>
            {% endfor %}
        </select>
    </div>
    <input type="submit" value="Ver" type="btn">
</form>
{% endblock %}

app/templates/clients/editar_cliente.html
{% extends "base.html" %}

{% block title %}Editar cliente | Quoter{% endblock title %}

{% block page_content %}

<section>
    <div>
        <form action="{{ url_for('clients.editar_cliente', cliente=cliente.nombre_corto) }}" method="POST">
            <div>
                <input type="text" name="razon_social" id="razon_social" value="{{ cliente.razon_social }}" placeholder="Razón Social" required>
            </div>
            <div>
                <input type="text" name="rfc" id="rfc" value="{{ cliente.rfc }}" placeholder="RFC" required>
            </div>
            <div>
                <input type="text" name="nombre_corto" id="nombre_corto" value="{{ cliente.nombre_corto }}" placeholder="Nombre corto" required>
            </div>
            <div>
                <input type="text" name="telefono" value="{{ cliente.telefono }}" placeholder="Teléfono de contacto">
            </div>
            <div>
                <input type="text" name="calle_numero" value="{{ cliente.calle_numero }}" placeholder="Calle y número">
            </div>
            <div>
                <input type="text" name="colonia" value="{{ cliente.colonia }}" placeholder="Colonia">
            </div>
            <div>
                <input type="text" name="municipio" value="{{ cliente.municipio }}" placeholder="Municipio">
            </div>
            <div>
                <input type="text" name="estado" value="{{ cliente.estado }}" placeholder="Estado">
            </div>
            <div>
                <input type="text" name="cp" id="cp" value="{{ cliente.cp }}" placeholder="Código Postal">
            </div>
            <div>
                <input type="submit" value="Guardar cambios"><a href="{{ url_for('clients.listado_clientes') }}">Cancelar</a>
            </div>
        </form>
    </div>
</section>

{% endblock page_content %}

{% block scripts %}

<script src="{{ url_for('static', filename='js/agregar_cliente.js') }}"></script>

{% endblock scripts %}

app/templates/clients/historial_cotizaciones.html
{% extends "base.html" %}

{% block title %}Historial de Cotizaciones | Quoter{% endblock title %}

{% block page_content %}

<header>
    <h1>Historial de cotizaciones por cliente</h1>
</header>

<section>
    <div>
        <p>
            <h2>{{ cliente.razon_social }}</h2>
        </p>
        <table>
            <thead>
                <tr>
                    <td>Folio</td>
                    <td>Fecha</td>
                    <td>Palabras clave</td>
                </tr>
            </thead>
            <tbody>
                {% for cotizacion in cotizaciones %}
                <tr>
                    <td>{{ cotizacion.folio }}</td>
                    <td>{{ cotizacion.fecha }}</td>
                    <td>{{ cotizacion.resumen }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>

{% endblock page_content %}

app/templates/clients/listado_clientes.html
{% extends "base.html" %}

{% block title %}Clientes | Quoter{% endblock title %}

{% block page_content %}
<header>
    <h1>Listado de clientes</h1>
</header>

<section>
    <div>
        <table>
            <thead>
                <tr>
                    <td>Razón Social</td>
                    <td>RFC</td>
                    <td>Información</td>
                    <td>Productos</td>
                    <td>Historial de cotizaciones</td>
                </tr>
            </thead>
            <tbody>
                {% for cliente in clientes %}
                <tr>
                    <td>{{ cliente.razon_social }}</td>
                    <td>{{ cliente.rfc }}</td>
                    <td>
                        <a href="{{ url_for('clients.editar_cliente', cliente=cliente.nombre_corto) }}">Detalles</a>
                    </td>
                    <td>
                        <a href="{{ url_for('products.listado_productos', cliente=cliente.nombre_corto) }}">Ver</a>
                    </td>
                    <td>
                        <a href="{{ url_for('clients.historial', cliente=cliente.nombre_corto) }}">Ver</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>

<section>
    <div>
        <p>
            <a href="{{ url_for('clients.agregar_cliente') }}">Agregar cliente</a>
        </p>
    </div>
</section>

{% endblock page_content %}